from __future__ import annotations

import gzip
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any
from grid_topology_ai.config import ReplayBufferConfig
from grid_topology_ai.self_play.example_validation import (
    load_and_validate_examples_csv,
    validate_example_outcome_contracts,
)
from grid_topology_ai.contracts import (
    OUTCOME_VALUE_TARGET_CONTRACT_VERSION,
    REPLAY_BUFFER_SCHEMA_VERSION,
    require_exact_contract_version,
)
from grid_topology_ai.physical_objective import PHYSICAL_OBJECTIVE_SCHEMA_VERSION

import numpy as np
import pandas as pd




def _json_safe(value: Any) -> Any:
    """
    Convert pandas/numpy values to JSON-safe Python values.
    """

    if value is None:
        return None

    if isinstance(value, (np.integer,)):
        return int(value)

    if isinstance(value, (np.floating,)):
        if np.isnan(value) or np.isinf(value):
            return None
        return float(value)

    if isinstance(value, (np.bool_,)):
        return bool(value)

    missing = pd.isna(value)

    if isinstance(missing, (bool, np.bool_)) and bool(missing):
        return None

    return value


def _row_to_json_safe_dict(row: dict[str, Any]) -> dict[str, Any]:
    return {
        str(key): _json_safe(value)
        for key, value in row.items()
    }


def _write_jsonl_gz(
    rows: list[dict[str, Any]],
    path: str | Path,
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with gzip.open(path, "wt", encoding="utf-8") as f:
        for row in rows:
            f.write(
                json.dumps(
                    _row_to_json_safe_dict(row),
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )
            f.write("\n")


def _read_jsonl_gz(path: str | Path) -> list[dict[str, Any]]:
    path = Path(path)

    rows: list[dict[str, Any]] = []

    if not path.exists():
        raise FileNotFoundError(f"Replay buffer file not found: {path}")

    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            text = line.strip()

            if not text:
                continue

            rows.append(json.loads(text))

    return rows


def _load_examples_csv(path: str | Path) -> list[dict[str, Any]]:
    df = load_and_validate_examples_csv(path)

    return [
        _row_to_json_safe_dict(row)
        for row in df.to_dict(orient="records")
    ]


def _require_replay_row_contracts(row: dict[str, Any], *, source: str) -> None:
    require_exact_contract_version(
        row.get("physical_objective_schema_version"),
        expected=PHYSICAL_OBJECTIVE_SCHEMA_VERSION,
        name="physical-objective contract",
        source=source,
        regeneration_command="python -m scripts.self_play.generate ...",
    )
    require_exact_contract_version(
        row.get("outcome_value_target_contract_version"),
        expected=OUTCOME_VALUE_TARGET_CONTRACT_VERSION,
        name="outcome/value-target contract",
        source=source,
        regeneration_command="python -m scripts.self_play.generate ...",
    )
    validate_example_outcome_contracts(pd.DataFrame([row]), source_path=source)


def _save_manifest(
    manifest: dict[str, Any],
    path: str | Path,
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _load_manifest(path: str | Path) -> dict[str, Any] | None:
    path = Path(path)

    if not path.exists():
        return None

    return json.loads(path.read_text(encoding="utf-8"))


class RollingReplayBuffer:
    """
    Rolling persistent replay buffer for hybrid pool-guided self-play.

    This class stores examples generated by self-play iterations.

    Important:
    - It does not save GridFM state tensors itself.
    - It assumes each example row already contains a valid state_path.
    - It preserves the CSV schema expected by GraphSelfPlayDataset.
    """

    def __init__(
        self,
        save_dir: str | Path,
        config: ReplayBufferConfig | None = None,
    ):
        self.save_dir = Path(save_dir)
        self.config = config or ReplayBufferConfig()

        self.save_dir.mkdir(parents=True, exist_ok=True)

        self.manifest_path = self.save_dir / "buffer_manifest.json"
        self.buffer: list[dict[str, Any]] = []

        self.load()

    def __len__(self) -> int:
        return len(self.buffer)

    def load(self) -> None:
        """
        Load existing replay buffer files from disk.

        Files are read from newest to oldest until max_size is reached.
        The final in-memory order is oldest -> newest so FIFO eviction works.
        """

        manifest = _load_manifest(self.manifest_path)

        if manifest is None:
            self.buffer = []
            return

        require_exact_contract_version(
            manifest.get("schema_version"),
            expected=REPLAY_BUFFER_SCHEMA_VERSION,
            name="replay-buffer schema",
            source=str(self.manifest_path),
            regeneration_command=(
                "remove or archive the legacy replay directory, then run "
                "python -m scripts.self_play.loop ..."
            ),
        )
        require_exact_contract_version(
            manifest.get("physical_objective_schema_version"),
            expected=PHYSICAL_OBJECTIVE_SCHEMA_VERSION,
            name="physical-objective contract",
            source=str(self.manifest_path),
            regeneration_command="python -m scripts.self_play.generate ...",
        )
        require_exact_contract_version(
            manifest.get("outcome_value_target_contract_version"),
            expected=OUTCOME_VALUE_TARGET_CONTRACT_VERSION,
            name="outcome/value-target contract",
            source=str(self.manifest_path),
            regeneration_command="python -m scripts.self_play.generate ...",
        )

        files = manifest.get("files", [])

        if not isinstance(files, list):
            raise ValueError(f"Invalid replay buffer manifest: {self.manifest_path}")

        selected_chunks: list[list[dict[str, Any]]] = []
        selected_count = 0

        for item in sorted(
                files,
                key=lambda value: int(
                    value.get("iteration", value.get("iter", 0))
                ),
                reverse=True,
        ):
            relative_path = item.get("path")
            if not relative_path:
                continue

            rows = _read_jsonl_gz(
                self.save_dir / str(relative_path)
            )
            for row_index, row in enumerate(rows):
                _require_replay_row_contracts(
                    row,
                    source=f"{relative_path} row {row_index}",
                )
            selected_chunks.append(rows)
            selected_count += len(rows)

            if selected_count >= self.config.max_size:
                break

        loaded = [
            row
            for chunk in reversed(selected_chunks)
            for row in chunk
        ]

        self.buffer = loaded[-self.config.max_size:]

    def _evict_if_needed(self) -> None:
        """
        FIFO eviction: remove the oldest examples first.
        """

        max_size = int(self.config.max_size)

        if max_size <= 0:
            raise ValueError("ReplayBufferConfig.max_size must be positive.")

        if len(self.buffer) <= max_size:
            return

        excess = len(self.buffer) - max_size
        self.buffer = self.buffer[excess:]

    def add_examples(
        self,
        examples: list[dict[str, Any]],
        *,
        iteration: int,
    ) -> None:
        """
        Add examples from one self-play iteration to the in-memory buffer.

        Low-level method: callers are responsible for validating rows before
        mutation when ingesting production self-play CSV data.
        """

        normalized: list[dict[str, Any]] = []

        for row in examples:
            item = _row_to_json_safe_dict(dict(row))
            _require_replay_row_contracts(
                item,
                source=f"replay iteration {iteration}",
            )
            item["replay_iteration"] = int(iteration)
            normalized.append(item)

        if len(normalized) >= int(self.config.max_size):
            print(
                "WARNING: Current iteration contains "
                f"{len(normalized)} examples, which is >= replay buffer max_size="
                f"{self.config.max_size}. FIFO eviction will remove all older examples. "
                "This is OK for a stress test, but for real self-play one iteration "
                "should normally be smaller than max_size."
            )

        self.buffer.extend(normalized)
        self._evict_if_needed()

    def add_examples_from_csv(
        self,
        examples_csv: str | Path,
        *,
        iteration: int,
    ) -> list[dict[str, Any]]:
        """
        Load examples.csv and add its rows to the buffer.
        """

        examples = _load_examples_csv(examples_csv)

        self.add_examples(
            examples=examples,
            iteration=iteration,
        )

        return examples

    def save_iteration_file(
        self,
        examples: list[dict[str, Any]],
        *,
        iteration: int,
    ) -> Path:
        """
        Save examples from one iteration to buffer_iter_XXX.jsonl.gz.
        """

        iteration = int(iteration)

        rows: list[dict[str, Any]] = []

        for row in examples:
            item = _row_to_json_safe_dict(dict(row))
            _require_replay_row_contracts(
                item,
                source=f"replay iteration {iteration}",
            )
            item["replay_iteration"] = iteration
            rows.append(item)

        output_path = self.save_dir / f"buffer_iter_{iteration:03d}.jsonl.gz"

        _write_jsonl_gz(
            rows=rows,
            path=output_path,
        )

        return output_path

    def save_manifest(self) -> None:
        """
        Rebuild and save buffer_manifest.json from existing buffer_iter files.
        """

        files: list[dict[str, Any]] = []

        for file_path in sorted(self.save_dir.glob("buffer_iter_*.jsonl.gz")):
            stem = file_path.name
            iteration_text = stem.replace("buffer_iter_", "").replace(".jsonl.gz", "")

            try:
                iteration = int(iteration_text)
            except ValueError:
                continue

            n = len(_read_jsonl_gz(file_path))

            files.append(
                {
                    "path": file_path.name,
                    "n": int(n),
                    "iteration": int(iteration),
                }
            )

        total_on_disk = int(sum(item["n"] for item in files))

        manifest = {
            "schema_version": REPLAY_BUFFER_SCHEMA_VERSION,
            "physical_objective_schema_version": (
                PHYSICAL_OBJECTIVE_SCHEMA_VERSION
            ),
            "outcome_value_target_contract_version": (
                OUTCOME_VALUE_TARGET_CONTRACT_VERSION
            ),
            "config": asdict(self.config),
            "total_examples_on_disk": total_on_disk,
            "total_examples_loaded": int(len(self.buffer)),
            "files": files,
        }

        _save_manifest(
            manifest=manifest,
            path=self.manifest_path,
        )

    def add_and_save_from_csv(
        self,
        examples_csv: str | Path,
        *,
        iteration: int,
    ) -> list[dict[str, Any]]:
        """
        Load examples.csv, add to memory, save iteration file, update manifest.
        """

        examples = _load_examples_csv(examples_csv)

        self.add_examples(
            examples=examples,
            iteration=iteration,
        )

        self.save_iteration_file(
            examples=examples,
            iteration=iteration,
        )

        self.save_manifest()

        return examples

    def _split_fresh_old(
        self,
        *,
        current_iteration: int,
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        fresh: list[dict[str, Any]] = []
        old: list[dict[str, Any]] = []

        for row in self.buffer:
            row_iteration = int(row.get("replay_iteration", -1))

            if row_iteration == int(current_iteration):
                fresh.append(row)
            else:
                old.append(row)

        return fresh, old

    def export_mixed_batch(
        self,
        output_path: str | Path,
        *,
        current_iteration: int,
        n_examples: int | None = None,
        fresh_fraction: float | None = None,
        seed: int | None = None,
    ) -> dict[str, Any]:
        """
        Export mixed train batch as CSV.

        Returns metadata describing how many fresh/old examples were used.
        """

        if len(self.buffer) < int(self.config.min_size_to_train):
            raise ValueError(
                f"Replay buffer has only {len(self.buffer)} examples, "
                f"but min_size_to_train={self.config.min_size_to_train}."
            )

        output_path = Path(output_path)

        if n_examples is None:
            n_total = len(self.buffer)
        else:
            n_total = min(int(n_examples), len(self.buffer))

        if n_total <= 0:
            raise ValueError("n_examples must be positive.")

        if fresh_fraction is None:
            fresh_fraction = float(self.config.fresh_fraction)

        fresh_fraction = float(np.clip(fresh_fraction, 0.0, 1.0))

        rng_seed = int(self.config.random_seed if seed is None else seed)
        rng = np.random.default_rng(rng_seed)

        fresh, old = self._split_fresh_old(
            current_iteration=current_iteration,
        )

        target_fresh = int(round(n_total * fresh_fraction))
        target_old = n_total - target_fresh

        n_fresh = min(target_fresh, len(fresh))
        n_old = min(target_old, len(old))

        # If one side is too small, fill from the other side.
        remaining = n_total - n_fresh - n_old

        if remaining > 0:
            fresh_left = len(fresh) - n_fresh
            take_more_fresh = min(remaining, fresh_left)
            n_fresh += take_more_fresh
            remaining -= take_more_fresh

        if remaining > 0:
            old_left = len(old) - n_old
            take_more_old = min(remaining, old_left)
            n_old += take_more_old
            remaining -= take_more_old

        if n_fresh + n_old <= 0:
            raise ValueError("Could not sample any examples from replay buffer.")

        selected: list[dict[str, Any]] = []

        if n_fresh > 0:
            fresh_indices = rng.choice(
                len(fresh),
                size=n_fresh,
                replace=False,
            )

            selected.extend(
                fresh[int(index)]
                for index in fresh_indices
            )

        if n_old > 0:
            old_indices = rng.choice(
                len(old),
                size=n_old,
                replace=False,
            )

            selected.extend(
                old[int(index)]
                for index in old_indices
            )

        rng.shuffle(selected)

        df = pd.DataFrame(selected)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(output_path, index=False)

        metadata = {
            "path": str(output_path),
            "n_examples": int(len(df)),
            "n_fresh": int(n_fresh),
            "n_old": int(n_old),
            "fresh_fraction_target": float(fresh_fraction),
            "fresh_fraction_actual": (
                float(n_fresh / len(df))
                if len(df) > 0
                else 0.0
            ),
            "current_iteration": int(current_iteration),
            "seed": int(rng_seed),
        }

        metadata_path = output_path.with_suffix(".metadata.json")
        _save_manifest(
            manifest=metadata,
            path=metadata_path,
        )

        return metadata

    def export_all(
        self,
        output_path: str | Path,
    ) -> Path:
        """
        Export the whole currently loaded buffer to CSV.

        Useful for debugging.
        """

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        df = pd.DataFrame(self.buffer)
        df.to_csv(output_path, index=False)

        return output_path
